format = """
[░▒▓](#a3aed2)\
$os\
$username\
[ ](bg:#769ff0 fg:#a3aed2)\
$directory\
[ ](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[ ](fg:#394260 bg:#212736)\
$buf\
$c\
$conda\
$docker_context\
$dotnet\
$golang\
$java\
$lua\
$nodejs\
$php\
$python\
$rust\
[](#212736)\
$fill\
[](#394260)\
$battery\
[](bg:#394260 fg:#1d2230)\
$time\
$line_break\
$character\
"""

[buf]
symbol = " "
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#394260)]($style)'

[battery]
format = '[ $symbol ($percentage) ](fg:#769ff0 bg:#394260)'
unknown_symbol = '󱉞'

[[battery.display]]
threshold = 10
discharging_symbol = '󱃍'
charging_symbol = '󰢟'

[[battery.display]]
threshold = 20
discharging_symbol = '󰁺'
charging_symbol = '󰢜'

[[battery.display]]
threshold = 30
discharging_symbol = '󰁻'
charging_symbol = '󰂆'

[[battery.display]]
threshold = 40
discharging_symbol = '󰁼'
charging_symbol = '󰂇'

[[battery.display]]
threshold = 50
discharging_symbol = '󰁽'
charging_symbol = '󰂈'

[[battery.display]]
threshold = 60
discharging_symbol = '󰁾'
charging_symbol = '󰢝'

[[battery.display]]
threshold = 70
discharging_symbol = '󰁿'
charging_symbol = '󰂉'

[[battery.display]]
threshold = 80
discharging_symbol = '󰂀'
charging_symbol = '󰢞'

[[battery.display]]
threshold = 90
discharging_symbol = '󰂁'
charging_symbol = '󰂊'

[[battery.display]]
threshold = 95
discharging_symbol = '󰂂'
charging_symbol = '󰂋'

[[battery.display]]
threshold = 100
discharging_symbol = '󰁹'
charging_symbol = '󰂄'

[c]
symbol = " "
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[conda]
symbol = " "
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[dart]
symbol = " "
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[docker_context]
symbol = " "
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[dotnet]
symbol = '󰪮 '
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[elixir]
symbol = " "
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[elm]
symbol = " "
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[fossil_branch]
symbol = " "
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = " "
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[guix_shell]
symbol = " "
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[haskell]
symbol = " "
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[haxe]
symbol = " "
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[hg_branch]
symbol = " "
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[hostname]
ssh_symbol = " "
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[java]
symbol = " "
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[julia]
symbol = " "
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[lua]
symbol = " "
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[memory_usage]
symbol = "󰍛 "
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[meson]
symbol = "󰔷 "
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[nix_shell]
symbol = " "
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'

[nodejs]
symbol = " "
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'


[package]
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'
symbol = "󰏗 "

[pijul_channel]
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'
symbol = " "

[python]
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'
symbol = " "

[rlang]
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'
symbol = "󰟔 "

[ruby]
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'
symbol = " "

[rust]
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'
symbol = " "

[scala]
style = "bg:#212736"
format = '[[$symbol($version) ](fg:#769ff0 bg:#212736)]($style)'
symbol = " "

# Functional
[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[$path ]($style)"
read_only = " 󰌾"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[fill]
symbol = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[$symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time  ](fg:#a0a9cb bg:#1d2230)]($style)'

[username]
show_always = true
style_user = "bg:#a3aed2 fg:#394260"
style_root = "bg:#a3aed2 fg:#ff757f"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:#a3aed2"
format = '[[ $symbol](bg:#a3aed2 fg:#769ff0)]($style)'
disabled = false

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "
